Month 8/step 1
AlekseyShaydullin/react-burger pull request #3
Opened 2022-11-03 17:31 UTC by AlekseyShaydullin

2022-11-03 18:15 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Хедер должен быть выравнен по центру.

- При отправке запроса на создание заказа `POST /orders`, в поле `ingredients` следует передавать обе булки, а не 1. Т.е. id булок должны быть в самом начале массива, и в конце, а также они должны быть одинаковы;

### **Сделает код лучше:**

- при клике на таб скролить список ингредиентов к нужному разделу

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-03 18:15 UTC, ArslanDev666 commented on src/components/App/App.jsx
>    const [currentIngredient, setCurrentIngredient] = useState({});
**Надо исправить:**

Если данных нет, то следует записывать null а не пустой объект

2022-11-03 18:15 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  const [orderState, setOrderState] = useState(0);
**Надо исправить:**

Тут тоже нужно указывать `null`, т.к изначально данных нет.

2022-11-03 18:15 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +        </IngredientsContext.Provider>
**Можно лучше:** Почему бы сразу не занести контекст в условие.

2022-11-03 18:15 UTC, ArslanDev666 commented on src/components/App/App.jsx
>        </Modal>
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```jsx
{isOpen && (
    компонент открываемого попапа
)}
```

Т.е. попап вообще не должен знать о том, открыт он или нет (Нужно убрать пропс `activeModal`).

2022-11-03 22:56 UTC, AlekseyShaydullin commented
В компоненте BurgerConstructor написана часть запроса на создание заказа POST /orders с комментарием

2022-11-04 04:40 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

По поводу вашего комментария, хорошо, замечание снимаю.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

### **Но все ещё есть несколько замечаний, которые нужно исправить:**

- Хедер должен быть выравнен по центру. https://yadi.sk/d/F6ELvVRYENsc_g

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу

2022-11-04 04:40 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +      )}
**Надо исправить:** тут можно обойтись без допольнительной переменной в виде `isOpenedIngredientsModal`. А просто проверять есть ли `currentIngredient` или нет.

2022-11-06 11:36 UTC, merged